### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by delaneyj** [abenz1267/LitElement-TypeScript-and-Webpack-Example#2]
The alert and button show up but the console contains...

```
decorators.js:21 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "action-button" has already been used with this registry
    at legacyCustomElement (webpack:///./node_modules/lit-element/lib/decorators.js?:21:27)
    at eval (webpack:///./node_modules/lit-element/lib/decorators.js?:47:5)
    at __decorate (webpack:///./src/components/button.ts?:7:95)
    at eval (webpack:///./src/components/button.ts?:28:16)
    at Module../src/components/button.ts (http://localhost:8080/bundle.js:661:1)
    at __webpack_require__ (http://localhost:8080/bundle.js:20:30)
    at eval (webpack:///./src/index.ts?:2:76)
    at Module../src/index.ts (http://localhost:8080/bundle.js:685:1)
    at __webpack_require__ (http://localhost:8080/bundle.js:20:30)
    at eval (webpack:///multi_(webpack)-dev-server/client?:2:18)
```

**Comment by abenz1267** [comment]
I know. Haven't found a fix yet. If you find one, let me know or do a PR.

Regards

**Comment by delaneyj** [comment]
[So I did find a fix](https://stackoverflow.com/questions/50355644/polymer-3-0-uncaught-dom-exception-when-using-paper-input)

```
const _customElementsDefine = window.customElements.define;
window.customElements.define = function(name, clazz, config) {
  if (!customElements.get(name)) {
    _customElementsDefine.call(window.customElements, name, clazz, config);
  }
};
``` 
in my index.ts before anything else.

**Comment by abenz1267** [comment]
Hi,

Yeah... That's one besides a few others I've found as well, but I'm not exactly sure if that's a fix, as in: it merely masks an underlying issue with how custom elements get registered in this stack.

You are masking an error that doesn't cause any actual issue. For peace of mind you can do that, but the issue seems to be rooted deeper.

F.e. why is the error only occuring for the first custom element, but not the second?

I always investigate this issue from time to time... but 'fixing' it like this isn't reasonable to me. What if the underlying issue gets resolved at one point? Need to remove this redundant fix then again.

As long as it works... Band-aiding this doesn't solve any problem.

Regards

**Comment by fcamblor** [comment]
On my side, I found it was due to 2 `bundle.js` being declared in the resulting html page.

I guess webpack is appending his own `<script>` tag to the DOM, while a `bundle.js` declaration already exists in the `src/index.html` file

=> when I removed `bundle.js` from `src/index.html` file, it solved this issue

**Comment by abenz1267** [comment]
Thanks a lot!
